package com.kodilla.vaadin.books.domain;

import java.util.Objects;
import java.util.UUID;

public class Book {
    private final UUID id;
    private String title;
    private String author;
    private String publicationYear;
    private BookType type;

    public Book() {
        this.id = UUID.randomUUID();
    }

    public Book(String title, String author, String publicationYear, BookType type) {
        this.id = UUID.randomUUID();
        this.title = title;
        this.author = author;
        this.publicationYear = publicationYear;
        this.type = type;
    }

    public UUID getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getAuthor() {
        return author;
    }

    public String getPublicationYear() {
        return publicationYear;
    }

    public BookType getType() {
        return type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Book book = (Book) o;
        return Objects.equals(id, book.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public void setPublicationYear(String publicationYear) {
        this.publicationYear = publicationYear;
    }

    public void setType(BookType type) {
        this.type = type;
    }

    /* version without id
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Book book = (Book) o;
        return Objects.equals(title, book.title)
                && Objects.equals(author, book.author)
                && Objects.equals(publicationYear, book.publicationYear)
                && Objects.equals(type, book.type);
    }
    */

    /* generated by IntelliJ IDEA
    @Override
    public int hashCode() {
        return Objects.hash(title, author, publicationYear, type);
    }
    */

    /* created manually --> less convenient to write but is a bit faster. good for big hash maps with millions of rows */
    /* version without id
    @Override
    public int hashCode() {
        int result = title != null ? title.hashCode() : 0;
        result = 31 * result + (author != null ? author.hashCode() : 0);
        result = 31 * result + (publicationYear != null ? publicationYear.hashCode() : 0);
        result = 31 * result + (type != null ? type.hashCode() : 0);
        return result;
    }
    */
}
