CREATE TABLE STATS (
    STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS CNT
FROM BOOKS
WHERE BESTSELLER = 1;

DELIMITER $$
CREATE EVENT UPDATE_BESTSELLERS_STATS
ON SCHEDULE EVERY 1 MINUTE
STARTS CURRENT_TIMESTAMP
DO
BEGIN
    CALL UpdateBestsellers();
    INSERT INTO STATS (STAT_DATE, STAT, VALUE)
    SELECT NOW(), 'BESTSELLERS', CNT
    FROM BESTSELLERS_COUNT;
END $$
DELIMITER ;

SHOW PROCESSLIST;
SELECT * FROM BOOKS;
DROP EVENT UPDATE_BESTSELLERS_STATS;
