use kodilla_course;

EXPLAIN SELECT *
FROM READERS
WHERE FIRSTNAME = 'John';

CREATE INDEX READERNO ON READERS(FIRSTNAME, LASTNAME);
CREATE INDEX BOOKNO ON BOOKS(TITLE);

EXPLAIN SELECT *
FROM READERS
WHERE FIRSTNAME = 'John';