use kodilla_course;

## BOOKS_AUD
# CREATE TABLE
CREATE TABLE BOOKS_AUD (
    EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
    EVENT_DATE DATETIME NOT NULL,
    EVENT_TYPE VARCHAR(10) DEFAULT NULL,
    BOOK_ID INT(11) NOT NULL,
    OLD_TITLE VARCHAR(255),
    NEW_TITLE VARCHAR(255),
    OLD_PUBYEAR INT(4),
    NEW_PUBYEAR INT(4),
    PRIMARY KEY (EVENT_ID)
);

# BOOKS_INSERT
DELIMITER $$
CREATE TRIGGER BOOKS_INSERT AFTER INSERT ON BOOKS
    FOR EACH ROW
BEGIN
   INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR)
       VALUE (CURTIME(), 'INSERT', NEW.BOOK_ID, NEW.TITLE, NEW.PUBYEAR);
END $$
DELIMITER ;

INSERT INTO BOOKS (TITLE, PUBYEAR) VALUE ('Harry Potter and the Philosopher''s Stone', 1997);
COMMIT;

# BOOKS_DELETE
DELIMITER $$
CREATE TRIGGER BOOKS_DELETE BEFORE DELETE ON BOOKS
    FOR EACH ROW
BEGIN
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID)
        VALUE (CURTIME(), 'DELETE', OLD.BOOK_ID);

    INSERT INTO RENTS_AUD (EVENT_DATE, EVENT_TYPE, RENT_ID)
        SELECT CURTIME(), 'DELETE', RENT_ID
        FROM RENTS WHERE BOOK_ID = OLD.BOOK_ID;
END $$
DELIMITER ;

DELETE FROM BOOKS WHERE BOOK_ID = 9;

# BOOKS_UPDATE
DELIMITER $$
CREATE TRIGGER BOOKS_UPDATE AFTER UPDATE ON BOOKS
    FOR EACH ROW
BEGIN
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, OLD_TITLE, NEW_TITLE, OLD_PUBYEAR, NEW_PUBYEAR)
        VALUE (CURTIME(), 'UPDATE', OLD.BOOK_ID, OLD.TITLE, NEW.TITLE,
               OLD.PUBYEAR, NEW.PUBYEAR);
END $$
DELIMITER ;

UPDATE BOOKS SET TITLE = 'The Trial TEST UPDATE'
WHERE BOOK_ID = 3;

COMMIT;

## READERS_AUD
# CREATE TABLE
CREATE TABLE READERS_AUD (
                           EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
                           EVENT_DATE DATETIME NOT NULL,
                           EVENT_TYPE VARCHAR(10) DEFAULT NULL,
                           READER_ID INT(11) NOT NULL,
                           OLD_FIRSTNAME VARCHAR(255),
                           NEW_FIRSTNAME VARCHAR(255),
                           OLD_LASTNAME VARCHAR(255),
                           NEW_LASTNAME VARCHAR(255),
                           OLD_PESELID VARCHAR(11),
                           NEW_PESELID VARCHAR(11),
                           PRIMARY KEY (EVENT_ID)
);

# READERS_INSERT
DELIMITER $$
CREATE TRIGGER READERS_INSERT AFTER INSERT ON READERS
    FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_FIRSTNAME, NEW_LASTNAME, NEW_PESELID)
        VALUE (CURTIME(), 'INSERT', NEW.READER_ID, NEW.FIRSTNAME, NEW.LASTNAME, NEW.PESELID);
END $$
DELIMITER ;

INSERT INTO READERS (FIRSTNAME, LASTNAME, PESELID) VALUE ('TOM', 'Cruz', '74022399838');
COMMIT;

# READERS_DELETE
DELIMITER $$
CREATE TRIGGER READERS_DELETE BEFORE DELETE ON READERS
    FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID)
        VALUE (CURTIME(), 'DELETE', OLD.READER_ID);

    INSERT INTO RENTS_AUD (EVENT_DATE, EVENT_TYPE, RENT_ID)
    SELECT CURTIME(), 'DELETE', RENT_ID
    FROM RENTS WHERE READER_ID = OLD.READER_ID;
END $$
DELIMITER ;

DELETE FROM READERS WHERE READER_ID = 3;

# READERS_UPDATE
DELIMITER $$
CREATE TRIGGER READERS_UPDATE AFTER UPDATE ON READERS
    FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, OLD_FIRSTNAME, NEW_FIRSTNAME, OLD_LASTNAME,
                             NEW_LASTNAME, OLD_PESELID, NEW_PESELID)
        VALUE (CURTIME(), 'UPDATE', OLD.READER_ID, OLD.FIRSTNAME,
               NEW.FIRSTNAME,OLD.LASTNAME, NEW.LASTNAME,
              OLD.PESELID, NEW.PESELID);
END $$
DELIMITER ;

UPDATE READERS SET FIRSTNAME = 'TOMMY'
WHERE READER_ID = 6;

COMMIT;
